title: Cyril George
logo: "/profile.png?raw=true"
description: > # Test Engineer
  <br><br>
  <a href="mailto:cyrilgeorge153@gmail.com"cyrilgeorge153@gmail.com. </a>
  <br>
  <a href="https://www.linkedin.com/in/cyril-george-3b9873bb/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/cyrilgeorge153/cyrilgeorge153">Gihub</a> 
theme: jekyll-theme-minimal
