title: Cyril George # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Lead Engineer, QA
  <br><br>
  <a href="mailto:cyrilgeorge153@gmail.com">Gmail</a>
  <br>
  <a href="https://www.linkedin.com/in/cyrilgeorge153/">Linkedin</a>
  <br>
  <br>
  <a href="https://www.qburst.com/software-testing-services/?ref=1500042">Quality Assurance Service</a>
  <br>
theme: jekyll-theme-minimal
