title: Cyril George # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Test Engineer
  <br><br>
  <a href="mailto:cyrilgeorge153@gmail.com">cyrilgeorge153@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/cyril-george-3b9873bb/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
