title: Cyril George # your name (or website title) here
<<<<<<< HEAD
logo: "/profile.jpg?raw=true" # your photo (or logo) here# your photo (or logo) here
=======
logo: "/profile.jpg?raw=true" # your photo (or logo) here
>>>>>>> 6c06d344a124496d6416c1aab257ba8398ff97f1
description: > # your text below (remove <br> elements if you don't need line breaks)
Lead Engineer, QA
  <br><br>
  <a href="mailto:cyrilgeorge153@gmail.com">cyrilgeorge153@gmail.com </a>
  <br>
  <a href="www.linkedin.com/in/cyrilgeorge153">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
