title: Cyril George # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Lead Engineer, QA
  <br><br>
  <a href="mailto:cyrilgeorge153@gmail.com">cyrilgeorge153@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/cyrilgeorge153/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/cyrilgeorge153/">Github</a> 
theme: jekyll-theme-minimal